spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rotacerta_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: rotacerta

application:
  security:
    jwt:
      secret-key: NGRmNTI1ZjZkYjM2NTM0YjM5MmM1OTYyN2M2ZTc4MzE2YjM4OTU3OWM5MjQ1ZGI5OWU4NzVjNzc0YjVjMmEyMw==
      expiration: 86400000
  shipping:
    melhor-envio:
      api-url: https://sandbox.melhorenvio.com.br
      api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI5NTYiLCJqdGkiOiI3Y2Q0YzI5YzBkZjFlODI1ZDUwNDBhNTY2MTUzMDBjZjc2OWQxZjkwOWExNzJiNGM1OTc0MDc0ZmU1ZjA5M2Q3MzcyMjBjOWQ2ZmRmMWExMCIsImlhdCI6MTc1NzE4MjQ5OS4zODI0NDksIm5iZiI6MTc1NzE4MjQ5OS4zODI0NTIsImV4cCI6MTc4ODcxODQ5OS4zNjk2NzUsInN1YiI6IjlmY2ViZWU5LTcyODAtNDQxMS04NzdkLWEzYzRiNjc0NTg1YSIsInNjb3BlcyI6WyJjYXJ0LXJlYWQiLCJjYXJ0LXdyaXRlIiwiY29tcGFuaWVzLXJlYWQiLCJjb21wYW5pZXMtd3JpdGUiLCJjb3Vwb25zLXJlYWQiLCJjb3Vwb25zLXdyaXRlIiwibm90aWZpY2F0aW9ucy1yZWFkIiwib3JkZXJzLXJlYWQiLCJwcm9kdWN0cy1yZWFkIiwicHJvZHVjdHMtZGVzdHJveSIsInByb2R1Y3RzLXdyaXRlIiwicHVyY2hhc2VzLXJlYWQiLCJzaGlwcGluZy1jYWxjdWxhdGUiLCJzaGlwcGluZy1jYW5jZWwiLCJzaGlwcGluZy1jaGVja291dCIsInNoaXBwaW5nLWNvbXBhbmllcyIsInNoaXBwaW5nLWdlbmVyYXRlIiwic2hpcHBpbmctcHJldmlldyIsInNoaXBwaW5nLXByaW50Iiwic2hpcHBpbmctc2hhcmUiLCJzaGlwcGluZy10cmFja2luZyIsImVjb21tZXJjZS1zaGlwcGluZyIsInRyYW5zYWN0aW9ucy1yZWFkIiwidXNlcnMtcmVhZCIsInVzZXJzLXdyaXRlIiwid2ViaG9va3MtcmVhZCIsIndlYmhvb2tzLXdyaXRlIiwid2ViaG9va3MtZGVsZXRlIiwidGRlYWxlci13ZWJob29rIl19.YdjHZEgGW8JViY3nsVEDlxpfC-xIHhhMm3kctk1LrsEIc5-WhQFdKk0TP4HsnxQcpTOe7t-C_1_iW1bgKXr3KTzL2CKMY6yWSPPGCw8VJx44eQLieoRkuhle8E3Yzee4MicDZv7L-orleWSV-pqgho2QkybQ5E1c1tKy-SxwfCzv5tL80JrR-7YT66qaeMplOMaj1rw76kFGI6VjrPFHaqVtX-5xbaTXVdKl0pd1_DqI1KF1ZIVCxiuibW-HIK69V9G0Szz312b_ZPLNCZ6YIv_V2l6XgZtUit_K1qzThi0lhMVSfp8VaPpsB7QrHklGNj3RsI-ROc3E5dNsUu0ePHwuVbzNMKbmaOBaW_9FJ0Y5D8B5ms2zUR7TBDxCb7hD0BmyrLO680ZCfV41jqTQKy3k9zCqOGfeqHmlu6ZKiUyfmAkOst_fcgvXJn2e7RVgYAxxSydSjtVNLZS5eVkx-7uern6sQuwcKl6s3FPXn84RSHJTS-o7StvqVT6WOIrIkis0a-KvmlvO-nMrhMbDxxvuMFS0ToipnWN-WF_8pDX3kZcW-JrtbbWRPBg2gpX0ftaAwMDgVzcYeuDpMt8KtnsDdUdqseFeF969mAUV12wtfqjmtCj31qWuoiSchzBoN9Lg4fKFeyx5QKhxozJ7l5lYis_iTbFaVnCKauGT234
      user-agent: "jaopvp7@gmail.com"
  api:
    stripe:
      secret-key: sk_test_51S4RLsPH4tTzeMs75FzjH0fiPqG7deuJOORA0dRuy7O4aEIjIMXZfjD1HJbwOdZIW4jfksM3tMIIspoIYb4BDcBM00udhI6CdI
      webhook-secret: whsec_70298bb0eb9d5fef43a7b1b65efb3ea246ac0cb0e72f9b13deb953a3042a772e

logging:
  level:
    org.springframework.security: DEBUG